In [2]:
my_list =[1,2,3,4,5,6]
print(my_list)

[1, 2, 3, 4, 5, 6]


In [1]:
import numpy as np

In [3]:
array = np.array( my_list ,dtype=int)
print(array)

[1 2 3 4 5 6]


In [4]:
print(len(array))
print(type(array))
print(array.ndim)
print(array.shape)
print(array.dtype)

6
<class 'numpy.ndarray'>
1
(6,)
int64


In [10]:
array2=(array.reshape(2,3))
print(array2)
array2.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
my_list2 = [1,2,3,4,5]
my_list3 = [2,3,4,5,6]
my_list4 = [9,7,6,8,9]
